obj-y  += wisehmi.o

//obj-y  += SHA204/bitbang_phys.o
obj-y  += SHA204/uart_phys.o
obj-y  += SHA204/sha204_comm.o
obj-y  += SHA204/sha204_comm_marshaling.o
obj-y  += SHA204/sha204_swi.o
obj-y  += SHA204/sha204_helper.o
obj-y  += SHA204/sha204_main_api.o
obj-y  += SHA204/sha204_read_write.o
obj-y  += SHA204/atsha204_enc_read.o
obj-y  += SHA204/rand_challenge.o
obj-y  += SHA204/tempkey.o

obj-y  += SHA204/mxc_gpio.o
